name: POC18 CI Workflow

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: dev

    steps:
      - name: Deploy to Dev EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_KEY }}
          port: 22
          script: |
            echo "Connected to DEV EC2"

            cd /home/$USER/POC-18/poc18-aws

            git checkout dev
            git pull origin dev

            sudo cp index.html /usr/share/httpd/noindex/index.html
            sudo systemctl restart httpd

            echo "DEV Deployment Successful!"


  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    environment: test

    steps:
      - name: Deploy to Test EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_EC2_HOST }}
          username: ${{ secrets.TEST_EC2_USER }}
          key: ${{ secrets.TEST_EC2_KEY }}
          port: 22
          script: |
            echo "Connected to TEST EC2"

            cd /home/$USER/POC-18/poc18-aws

            git checkout test
            git pull origin test

            sudo cp index.html /usr/share/httpd/noindex/index.html
            sudo systemctl restart httpd

            echo "TEST Deployment Successful!"


  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: prod

    steps:
      - name: Deploy to Prod EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_EC2_KEY }}
          port: 22
          script: |
            echo "Connected to PROD EC2"

            cd /home/$USER/POC-18/poc18-aws

            git checkout main
            git pull origin main

            sudo cp index.html /usr/share/httpd/noindex/index.html
            sudo systemctl restart httpd

            echo "PROD Deployment Successful!"
